version: '3'

services:
 
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672" 
    command: rabbitmq-server
    networks: 
      - myappnet
  
  backend:
    build: .
    ports:
      - "80:8000"
    networks:
      - myappnet  
    restart: on-failure
    depends_on:
      - rabbit
    command: nameko run backendserver --broker amqp://guest:guest@10.0.1.17:5672

networks:
  myappnet: 
