aws_config = (JSON.parse(File.read("aws-multiple.json")))

Vagrant.configure("2") do |config|

    config.vm.box = "aws-dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "./provision/installdocker.sh"
    
    config.vm.provision "docker_sudo", type:"shell", inline: <<-SHELL
      sudo yum update -y
      sudo yum install -y docker
      sudo service docker start
      sudo usermod -a -G docker ec2-user
    SHELL

    #config.vm.provisioin "install_docker-compose", type:"shell", inline: <<-SHELL
    #  sudo apt install -y docker-compose
    #SHELL


    aws_config['manager']['instances'].each do |instance|
        instance_key   = instance[0]
        instance_value = instance[1]



        config.vm.define instance_key do |config2|
	    ec2_tags = instance_value['tags']
        #config2.vm.provision "shell", path: "./provision/installdocker.sh"        
    
            config2.vm.provider :aws do |ec2, override|
                ec2.keypair_name = aws_config['manager']['keypair_name']
                ec2.subnet_id = aws_config['manager']['subnet_id']
                ec2.security_groups = [ aws_config['manager']['security_groups'] ]
                ec2.ami = instance_value['ami_id']
                ec2.instance_type = instance_value['instance_type']
                ec2.tags = {
			        'Name' => ec2_tags['Name']
	        	}
	        	override.ssh.username = aws_config['manager']['ssh_username']
                override.ssh.private_key_path = aws_config['manager']['ssh_private_key_path']
            end

        end
    end


    aws_config['worker']['instances'].each do |instance|
        instance_key   = instance[0]
        instance_value = instance[1]

        config.vm.define instance_key do |config3|
	    ec2_tags = instance_value['tags']
        #config3.vm.provision "shell", path: "./provision/installdocker.sh"

            config3.vm.provider :aws do |ec2, override|
                ec2.keypair_name = aws_config['worker']['keypair_name']
                ec2.subnet_id = aws_config['worker']['subnet_id']
                ec2.security_groups = [ aws_config['manager']['security_groups'] ]
                ec2.ami = instance_value['ami_id']
                ec2.instance_type = instance_value['instance_type']
                ec2.tags = {
			        'Name' => ec2_tags['Name']
	        	}
	        	override.ssh.username = aws_config['worker']['ssh_username']
                override.ssh.private_key_path = aws_config['worker']['ssh_private_key_path']
            end

        end
    end

end
