# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Provision
  config.vm.provision "shell", path: "./docker_provision.sh" 


  # Network settings
  # config.vm.network "public_network", ip: "192.168.0.17"

  
  # Folder settings
  config.vm.synced_folder ".", "/vagrant", disabled: true 


  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    # Read AWS authentication information from environment variables
    # aws.access_key_id = ENV['admin_AWS_ACCESS_KEY_ID']
    # aws.secret_access_key = ENV['admin_AWS_SECRET_ACCESS_KEY']
    #aws.aws_profile = 'Administrator'  
  
    aws.subnet_id = 'subnet-02d53692d320b5c41'
    aws.security_groups = ['sg-00d77c00d542369d0']
    
    # Specify SSH keypair to use
    aws.keypair_name = 'admin-key-us-west-1'

    # Specify region, AMI ID, and security group(s)
    aws.instance_type = "t2.micro"
    aws.ami = 'ami-06ff511fea5db2c99'
    aws.tags = { 'Name' => 'tomcat_in_container_in_ec2' }
    # Specify username and private key path
    override.ssh.username = 'ec2-user'
    override.ssh.private_key_path = '/Users/Jerry/.ssh/zxc22022444/ZAdministrator/admin-key-us-west-1.pem'
  end
end
