aws_config = (JSON.parse(File.read("aws-multiple.json")))

Vagrant.configure("2") do |config|

    config.vm.box = "aws-dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "./provision/installdocker.sh"
    
    config.vm.provision "installdocker", type:"shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      sudo apt update -y
      apt-cache policy docker-ce
      sudo apt install -y docker-ce=18.06.1~ce~3-0~ubuntu
      sudo systemctl status docker
      sudo usermod -a -G docker ubuntu
    SHELL

    config.vm.provision "installkube", type:"shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get install -y apt-transport-https curl
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      sudo bash -c "cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF"
      apt-get update -y
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl
    SHELL

    


    aws_config['manager']['instances'].each do |instance|
        instance_key   = instance[0]
        instance_value = instance[1]



        config.vm.define instance_key do |config2|
	    ec2_tags = instance_value['tags']
        #config2.vm.provision "shell", path: "./provision/installdocker.sh"        
    
            config2.vm.provider :aws do |ec2, override|
                ec2.keypair_name = aws_config['manager']['keypair_name']
                ec2.subnet_id = aws_config['manager']['subnet_id']
                ec2.security_groups = [ aws_config['manager']['security_groups'] ]
                ec2.ami = instance_value['ami_id']
                ec2.instance_type = instance_value['instance_type']
                ec2.tags = {
			        'Name' => ec2_tags['Name']
	        	}
	        	override.ssh.username = aws_config['manager']['ssh_username']
                override.ssh.private_key_path = aws_config['manager']['ssh_private_key_path']
            end

        end
    end


    aws_config['worker']['instances'].each do |instance|
        instance_key   = instance[0]
        instance_value = instance[1]

        config.vm.define instance_key do |config3|
	    ec2_tags = instance_value['tags']
        #config3.vm.provision "shell", path: "./provision/installdocker.sh"

            config3.vm.provider :aws do |ec2, override|
                ec2.keypair_name = aws_config['worker']['keypair_name']
                ec2.subnet_id = aws_config['worker']['subnet_id']
                ec2.security_groups = [ aws_config['worker']['security_groups'] ]
                ec2.ami = instance_value['ami_id']
                ec2.instance_type = instance_value['instance_type']
                ec2.tags = {
			        'Name' => ec2_tags['Name']
	        	}
	        	override.ssh.username = aws_config['worker']['ssh_username']
                override.ssh.private_key_path = aws_config['worker']['ssh_private_key_path']
            end

        end
    end

end
